DEFAULT_MAP_WIDTH = 20
DEFAULT_MAP_HEIGHT = 15

CELL_EMPTY = 0
CELL_TREE = 1
CELL_RIVER = 2
CELL_FIRE = 3
CELL_BURNT = 4
CELL_HOSPITAL = 5
CELL_SHOP = 6
CELL_CLOUD = 7

CELL_IMAGES = {
    CELL_EMPTY: "🟩",
    CELL_TREE: "🌲",
    CELL_RIVER: "🌊",
    CELL_FIRE: "🔥",
    CELL_BURNT: "🟫",
    CELL_HOSPITAL: "🏥",
    CELL_SHOP: "🏪",
    CELL_CLOUD: "☁️"
}

HELICOPTER_IMAGE = "🚁"

INITIAL_LIVES = 3
INITIAL_SCORE = 0
INITIAL_WATER_CAPACITY = 1
INITIAL_WATER = 0

SCORE_TREE_SAVED = 100
SCORE_TREE_BURNT = -50
SCORE_FIRE_SPREAD = -25

TREE_SPAWN_CHANCE = 0.02
FIRE_SPAWN_CHANCE = 0.1
FIRE_SPREAD_CHANCE = 0.3
CLOUD_SPAWN_CHANCE = 0.05
LIGHTNING_CHANCE = 0.1

TICKS_PER_FIRE_SPREAD = 3
TICKS_PER_TREE_GROW = 5

UPGRADE_WATER_CAPACITY_COST = 500
HEAL_COST = 200

RAIN_DURATION = 5
